server:
  port: ${SERVER_PORT:8080}


idp:
  proto: http
  host: localhost
  port: 8484
  url: ${idp.proto}://${idp.host}:${idp.port}
  realm: my_realm

spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak-resource}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8484/auth/realms/my_realm/protocol/openid-connect/certs}

      client:
        clientId: my_client
        client_secret: 8e730d63-911a-4d32-8c15-a52c4be87af4
        access-token-uri: ${idp.url}/auth/realms/${idp.realm}/protocol/openid-connect/token
        revoke-token-uri: ${idp.url}/auth/realms/${idp.realm}/protocol/openid-connect/revoke

logging:
  level:
    web: trace
    org.springframework.security: debug